### ISSUE TITLE
Fractions of RX and TX packets?

### ISSUE THREAD

**Issue by samwathegreat** [0x9900/igate_telem#5]
This project is great!  I love the easy integration with DireWolf.  I'm having an issue with the RX and TX packet counter.  It is showing fractions of packets.  Please see:  

![image](https://user-images.githubusercontent.com/4813336/152663348-3b4fbc79-e92e-4fa7-b2a3-3c4f627ec6f0.png)

Any idea what is causing this strange behavior?  I'm running the latest Raspberry OS - (bullseye).

Thanks in advance.

**Comment by 0x9900** [comment]
Fixed

**Comment by samwathegreat** [comment]
Thanks for the quick reply -- but that actually created a new issue and did not solve the fractional packets issue.  Now memory shows an outrageous amount (x1024) of free memory, and the packet issue remains the same.

![image](https://user-images.githubusercontent.com/4813336/152665712-57dd83f6-0c4d-4b15-ac3f-e132390bbf76.png)

EDIT:  I'm re-testing, I didn't see all of the changes that were made.  Please allow me a moment.

**Comment by samwathegreat** [comment]
OK, that was my mistake.  The RX and TX packets are now showing whole numbers.  Great!

I'm wondering though - how exactly these numbers are calculated though.  Because I can watch the data in direwolf, and I receive many packets during a 5 minute period.  Not just 2.  I'm not familiar enough with the code to understand how it is calculating these numbers.  Can you explain the rx and tx packet methodology?  This is an RX only iGate, so I'd expect the tx packets to always be 0 (which it is after applying the bugfix).  But I'm receiving far more packets than telemetry indicates.

Is it only counting directly heard packets (not digipeated packets)?

![image](https://user-images.githubusercontent.com/4813336/152665925-fe016650-3967-468f-9a9a-7d1a95c307ee.png)

**Comment by 0x9900** [comment]
The number represent the numbers of packet per seconds. An APRS gate doesn’t usually send a lot of packet, that’s why that number remains low. I have changed to code to send the number of packet since last run. I am currently testing it on my igate, I will push the new version of the code latter during the day. 

BTW, thank you for your feedback and your participation to this code. 

I don’t know if you have ever used aprsdirect.com <http://aprsdirect.com/> but that site can show you the coverage of your gateway. It looks like you have a good coverage.


73
-fred-


-- 
Fred C.
***@***.***
https://0x9900.com/ <https://0x9900.com/>
https://www.qrz.com/db/W6BSD <https://www.qrz.com/db/W6BSD>

**Comment by samwathegreat** [comment]
Fred,

Thanks!  You are very quick!  When I was browsing through the code I
noticed that it's looking for a physical interface like eth0.  Since I'm
using direwolf directly as TNC I'm wondering how exactly it's able to count
my packets.  Just for educational purposes only... Your coding abilities
are far beyond mine.

I look forward to trying out the new code :)

Thanks and 73

**Comment by 0x9900** [comment]
First I look at inside the file `/proc/net/route` to determine which one is the default interface (the interface the system use to reach the internet). Then I get the packets informations corresponding the to default interface from "/proc/net/dev”. 

The new version is online. In the graph you should see more packets now. Especially when you are using your gateway as a TNC.

BTW I am on the digital modes Dstar, C4FM and DMR, if you can work these modes we could have a chat.

73,

-fred-

-- 
Fred C.
***@***.***
https://0x9900.com/ <https://0x9900.com/>
https://www.qrz.com/db/W6BSD <https://www.qrz.com/db/W6BSD>

**Comment by samwathegreat** [comment]
Fred,

Thanks for the explanation.  So it seems that it is calculating total packets in and out of the default interface.  My number are much higher now, as expected.  I was hoping for it to show me the actual number of APRS packets received and transmitted as that would be most useful as telemetry for my station, but I'm guessing there is no good way to do that....

I wonder if we could use direwolf's own logs to calculate these.  The built in telemetry functionality for direwolf is over my head...but I'm finding that the other internet traffic on my machine significantly skews the rx and tx packets such that they aren't useful for APRS telemetry.  This station (KS9N-1) doesn't receive anywhere new this many aprs packets.

![image](https://user-images.githubusercontent.com/4813336/152726922-1dfb2f71-d495-48f1-906b-7dff8985d002.png)
